baseURL = 'http://example.org/'
languageCode = 'es-es'

#CanonifyURLs=true

theme = "ramium"

title = "Ben Galego"
disqusShortname = "disqus-code"
googleAnalytics = "analytics-code"
pluralizeListTitles = false
enableemoji = false

[params]
    description = "Recetas y ... gallegas"
    googleSearch = "google-search-code"
    adsense = "ca-pub-2159613976156530"
    googleAnalytics = 'G-XP6ZKZTPKK'
    showDate = true # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page
    githubLink = "egomezbpedro/ramium/"

    tagsInHome = 40     # set zero to not show in home page
    sectionsInHome = 5  # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Inicio"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Contenido"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Etiquetas"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Secciones"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Publicaciones"
                url = "/posts/"
                weight = 3
    
    [[menu.main]]
        name = "Acerca de"
        url = "/authorr/"
        weight = 3
